import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Providers from "@/src/app/Providers";
import Header from "../components/header";
import Sidebar from "../components/sidebar";
import Footer from "../components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "洲通能源科技有限公司",
    description: "Generated by create next app",
    icons: {
        icon: "/img/favicon.ico",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <Header />
                    <Sidebar />
                    <div style={{ height: "80px" }} />
                    {children}
                    <Footer />
                </Providers>
            </body>
        </html>
    );
}