import type { Metadata } from "next";
import { ReactElement } from "react";
import { dir } from "i18next";
import { languages } from "@/src/i18n/settings";
import { Inter } from "next/font/google";
import "./globals.css";

import favicon from "@/public/img/favicon.ico";
import Providers from "@/src/app/[lng]/Providers";
import { Header } from "@/src/components/Header/client";
import { Sidebar } from "@/src/components/Sidebar/client";
import { Footer } from "../../components/Footer/client";

const inter = Inter({ subsets: ["latin"] });

type RootLayoutProps = { children: ReactElement; params: { lng: string } };
export async function generateStaticParams() {
    return languages.map((lng) => ({ params: { lng } }));
}

export const metadata: Metadata = {
    title: "洲通能源科技有限公司",
    description: "Generated by create next app",
    icons: {
        icon: favicon.src,
    },
};

export default function RootLayout({
    children,
    params: { lng },
}: RootLayoutProps) {
    return (
        <html lang={lng} dir={dir(lng)}>
            <body className={inter.className}>
                <Providers>
                    <Header lng={lng}/>
                    <Sidebar lng={lng}/>
                    <div style={{ height: "80px" }} />
                    {children}
                    <Footer lng={lng}/>
                </Providers>
            </body>
        </html>
    );
}